<!-- changelog.inc -->

<h3>Version 1.1.3 - 19 March 2024</h3>
<ul>
   <li>New feature - Added Random Summary Sorting</li>
   <li>revert changelog to /doc/changelog.inc</li>
</ul><br>


<h3>Version 1.1.2 - 06Dec23</h3>
<ul>
   <li>Bug Fix - when adding comment - query may fail.</li>
   <li>Minor bug fix - author_ip not available in success message - fixed</li>
</ul><br>


<h3>Version 1.1.1 - 26May23</h3>
<ul>
   <li>Bug Fix - import from CGFeedback.</li>
   <li>Review submission within other modules fix</li>
</ul><br>


<h3>Version 1.1 - 20Feb23</h3>
<ul>
   <li>Bug Fixes.</li>
   <li>Review submission within other modules fix</li>
</ul><br>


<h3>Version 1.0 - 06Dec22</h3>
<ul>
   <li>First release of module, that is a fork of CGFeedback.</li>
   <li>Upgraded to work with PHP8, and CMSMSExt module (replacing CGExtensions)</li>
   <li>Full import of all CGFeedback reviews, settings & templates.</li>
   <li>'ReviewManager Radio Comment Form' uses stars for rating selection</li>
   <li>New reviews can be added directly in the admin pages (optionally)</li>
   <li>Review dates can be added in the admin pages.</li>
</ul>